name: Dominó
rules:
  - { image: Fondo.png, { when: { black: 0, blue: 0, green: 0, red: 0 } }
  - { image: 0_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 0 } }
  - { image: 0_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 0 } }
  - { image: 0_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 0 } }
  - { image: 0_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 0 } }
  - { image: 0_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 0 } }
  - { image: 0_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 0 } }
  - { image: 0_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 0 } }
  - { image: 0_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 0 } }
  - { image: 0_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 0 } }
  - { image: 0_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 0 } }
  - { image: 0_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 0 } }
  - { image: 0_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 0 } }
  - { image: 0_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 0 } }
  - { image: 0_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 0 } }
  - { image: 1_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 1 } }
  - { image: 1_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 1 } }
  - { image: 1_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 1 } }
  - { image: 1_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 1 } }
  - { image: 1_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 1 } }
  - { image: 1_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 1 } }
  - { image: 1_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 1 } }
  - { image: 1_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 1 } }
  - { image: 1_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 1 } }
  - { image: 1_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 1 } }
  - { image: 1_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 1 } }
  - { image: 1_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 1 } }
  - { image: 1_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 1 } }
  - { image: 1_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 1 } }
  - { image: 2_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 2 } }
  - { image: 2_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 2 } }
  - { image: 2_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 2 } }
  - { image: 2_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 2 } }
  - { image: 2_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 2 } }
  - { image: 2_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 2 } }
  - { image: 2_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 2 } }
  - { image: 2_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 2 } }
  - { image: 2_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 2 } }
  - { image: 2_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 2 } }
  - { image: 2_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 2 } }
  - { image: 2_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 2 } }
  - { image: 2_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 2 } }
  - { image: 2_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 2 } }
  - { image: 3_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 3 } }
  - { image: 3_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 3 } }
  - { image: 3_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 3 } }
  - { image: 3_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 3 } }
  - { image: 3_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 3 } }
  - { image: 3_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 3 } }
  - { image: 3_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 3 } }
  - { image: 3_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 3 } }
  - { image: 3_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 3 } }
  - { image: 3_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 3 } }
  - { image: 3_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 3 } }
  - { image: 3_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 3 } }
  - { image: 3_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 3 } }
  - { image: 3_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 3 } }
  - { image: 4_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 4 } }
  - { image: 4_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 4 } }
  - { image: 4_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 4 } }
  - { image: 4_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 4 } }
  - { image: 4_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 4 } }
  - { image: 4_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 4 } }
  - { image: 4_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 4 } }
  - { image: 4_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 4 } }
  - { image: 4_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 4 } }
  - { image: 4_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 4 } }
  - { image: 4_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 4 } }
  - { image: 4_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 4 } }
  - { image: 4_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 4 } }
  - { image: 4_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 4 } }
  - { image: 5_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 5 } }
  - { image: 5_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 5 } }
  - { image: 5_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 5 } }
  - { image: 5_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 5 } }
  - { image: 5_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 5 } }
  - { image: 5_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 5 } }
  - { image: 5_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 5 } }
  - { image: 5_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 5 } }
  - { image: 5_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 5 } }
  - { image: 5_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 5 } }
  - { image: 5_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 5 } }
  - { image: 5_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 5 } }
  - { image: 5_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 5 } }
  - { image: 5_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 5 } }
  - { image: 6_0_h.png, { when: { black: 0, blue: 1, green: 0, red: 6 } }
  - { image: 6_0_v.png, { when: { black: 0, blue: 2, green: 0, red: 6 } }
  - { image: 6_1_h.png, { when: { black: 0, blue: 1, green: 1, red: 6 } }
  - { image: 6_1_v.png, { when: { black: 0, blue: 2, green: 1, red: 6 } }
  - { image: 6_2_h.png, { when: { black: 0, blue: 1, green: 2, red: 6 } }
  - { image: 6_2_v.png, { when: { black: 0, blue: 2, green: 2, red: 6 } }
  - { image: 6_3_h.png, { when: { black: 0, blue: 1, green: 3, red: 6 } }
  - { image: 6_3_v.png, { when: { black: 0, blue: 2, green: 3, red: 6 } }
  - { image: 6_4_h.png, { when: { black: 0, blue: 1, green: 4, red: 6 } }
  - { image: 6_4_v.png, { when: { black: 0, blue: 2, green: 4, red: 6 } }
  - { image: 6_5_h.png, { when: { black: 0, blue: 1, green: 5, red: 6 } }
  - { image: 6_5_v.png, { when: { black: 0, blue: 2, green: 5, red: 6 } }
  - { image: 6_6_h.png, { when: { black: 0, blue: 1, green: 6, red: 6 } }
  - { image: 6_6_v.png, { when: { black: 0, blue: 2, green: 6, red: 6 } }
